[versions]
mapstruct = "1.6.3"
errorprone = "2.45.0"
assertj = "3.27.6"
wiremock = "3.13.2"
mockito = "5.21.0"
rest-assured = "6.0.0"
spotless = "8.1.0"
jacoco = "0.8.14"

[libraries]
# MapStruct
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

# Error Prone
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }

# Testing
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
wiremock = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }

# Plugins
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
